name: CI

on: [ push ]

jobs:
  pact:
    name: Run Pact tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Installation
        run: npm ci
      - name: Run pact tests
        run: npm run test:pact

